### ISSUE TITLE
Requesting new level instance does not populate contract var

### ISSUE THREAD

**Issue by gcutrini** [OpenZeppelin/ethernaut#198]
On Firefox, tested Level 0 or Level 1, when clicking on 'Get new Instance' button, it does request new instance but after confirming MetaMask transaction, only getting a MetaMask notification 'Transaction X Confirmed'.
On console, contract still has "No contract set, go to a level and click 'Get new instance'" value.

**Comment by abcoathup** [comment]
Hi @gcutrini!  

We can reproduce this issue using Firefox.  Thanks so much for reporting it! 
I assume this is caused by the MetaMask breaking changes which rolled out to Firefox first, as I had the issue on Firefox but not on Brave: https://medium.com/metamask/breaking-changes-to-the-metamask-provider-are-here-7b11c9388be9

The project owner will review and triage this issue as soon as they can.  

In the meantime, you can try the following workaround:
You can use an alternate browser such as Brave or Chrome.

**Comment by fmaduakor** [comment]
Workaround with Brave/Chrome does not seem to work anymore

**Comment by frangio** [comment]
Thank you all for reporting the issue. Unfortunately we don't have the bandwidth to fix this at the moment, so we've put up a maintenance page until we can, or someone helps us with the necessary changes.

**Comment by hackingbeauty** [comment]
In order to upgrade this project to the latest version of web3, we may need to resolve other relevant npm dependencies as well.

I tried upgrading web3 for this project; however, the Webpack config has been preventing me from booting up the project after I upgrade.

Is it OK if I issue a PR with a completely new Webpack config?  The new Webpack config would be more readable and easier to configure.
