### ISSUE TITLE
Rinkeby will be deprecated in few days

### ISSUE THREAD

**Issue by siddhpurakaran** [OpenZeppelin/ethernaut#402]
Rinkeby will be deprecated in few days so most of faucets already stopped working.....and now i don't have Rinkeby Ether and So i am not able to play game.

Please move to other stable testnet so people can play and learn smart contract security principles

:smiley: :)

**Comment by eliashezron** [comment]
hey, Still getting a 404 error on connecting to ethernaut despite switching to goerli and sepolia. 
I have cleared the cache but still failing to connect.

**Comment by xaler5** [comment]
Can you share the url that gives you 404? Also a screen showing metamask connected to the network would be useful

**Comment by eliashezron** [comment]
I can successfully connect my wallet, however on trying to access a level, I get the 404 error.
![ozerr](https://user-images.githubusercontent.com/60871378/194704461-fccd0c5e-13b4-427d-876d-a38b13b023ba.jpg)
https://ethernaut.openzeppelin.com/404

**Comment by xaler5** [comment]
@eliashezron this is still weird. I see you have multiple wallets (Coinbase and Metamask). I just tested it again and I'm able to play nicely on Goerli.

Can you try a new private window with just metamask enabled ? Would it be nice to see also Metamask opened and connected to the wallet in the screenshot.

**Comment by eliashezron** [comment]
@xaler5 it works perfectly after I disabled the coinbase wallet extension and was left with only metamask.

however, I don't see the levels I completed as checked since am using the same address as before.

Nonetheless, thank you. 
![oze](https://user-images.githubusercontent.com/60871378/194847392-0657982e-2235-4acf-b2cc-525f9f2033be.jpg)


however, considering that it was working just fine with multiple extension browser wallets installed prior to rinkeby being deprecated. And many devs work/have multiple browser wallets, it would be nice if it could work just fine despite having multiple browser wallets.
